# Generated by Django 3.2.6 on 2021-08-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
                ('mois', models.CharField(max_length=255)),
                ('année', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SCF', models.CharField(max_length=255)),
                ('banques', models.CharField(max_length=255)),
                ('moism1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('moism', models.DecimalField(decimal_places=5, max_digits=20)),
                ('observation', models.CharField(max_length=255)),
                ('canva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tresorerie_canva', to='bilans.canva')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=255)),
                ('unité', models.CharField(max_length=255)),
                ('mois1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('mois2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('ecart1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('evolution1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('finmois1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('finmois2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('ecart2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('evolution2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('canva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_canva', to='bilans.canva')),
            ],
        ),
        migrations.CreateModel(
            name='Bilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregat', models.CharField(max_length=255)),
                ('SCF', models.CharField(max_length=255)),
                ('mois1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('mois2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('ecart1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('evolution1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('finmois1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('finmois2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('ecart2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('evolution2', models.DecimalField(decimal_places=5, max_digits=20)),
                ('canva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilan_canva', to='bilans.canva')),
            ],
        ),
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autreag', models.CharField(max_length=255)),
                ('SCF', models.CharField(max_length=255)),
                ('finmoisn1', models.DecimalField(decimal_places=5, max_digits=20)),
                ('finmoisn', models.DecimalField(decimal_places=5, max_digits=20)),
                ('ecart', models.DecimalField(decimal_places=5, max_digits=20)),
                ('evolution', models.DecimalField(decimal_places=5, max_digits=20)),
                ('canva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autre_canva', to='bilans.canva')),
            ],
        ),
    ]
