# Generated by Django 3.2.6 on 2021-08-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0005_auto_20210812_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canva',
            name='année',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='canva',
            name='mois',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='canva',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='canva',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
