# Generated by Django 3.2.6 on 2021-08-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0008_auto_20210812_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autre',
            name='SCF',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='autreag',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='ecart',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='evolution',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='finmoisn',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='finmoisn1',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20, null=True),
        ),
    ]
