# Generated by Django 3.2.6 on 2021-08-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0011_auto_20210815_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan',
            name='validation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
