# Generated by Django 3.2.6 on 2021-08-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0013_auto_20210818_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validation',
            old_name='test',
            new_name='box',
        ),
    ]
