# Generated by Django 3.2.6 on 2021-08-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0014_rename_test_validation_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='box',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
