# Generated by Django 3.2.6 on 2021-08-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0015_alter_validation_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validation',
            name='box',
        ),
        migrations.AddField(
            model_name='validation',
            name='test',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
