# Generated by Django 3.2.6 on 2021-08-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0016_auto_20210818_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='canva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_canva', to='bilans.canva'),
        ),
    ]
