# Generated by Django 3.2.6 on 2021-08-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0017_validation_canva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
