# Generated by Django 3.2.6 on 2021-08-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0020_alter_canva_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canva',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
