# Generated by Django 3.2.6 on 2021-08-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0021_alter_canva_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='validation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
