# Generated by Django 3.2.6 on 2021-08-19 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0022_canva_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkbox',
            fields=[
                ('validation', models.BooleanField(default=False)),
                ('canva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bilans.canva')),
            ],
        ),
        migrations.RemoveField(
            model_name='canva',
            name='validation',
        ),
    ]
