# Generated by Django 3.2.6 on 2021-08-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0024_alter_checkbox_canva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbox',
            name='validation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
