# Generated by Django 3.2.6 on 2021-08-19 23:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0025_alter_checkbox_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkbox',
            name='canva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkbox_canva', to='bilans.canva'),
        ),
    ]
