# Generated by Django 3.2.6 on 2021-08-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0027_auto_20210820_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='id',
            field=models.IntegerField(auto_created=1, default=5),
            preserve_default=False,
        ),
    ]
