# Generated by Django 3.2.6 on 2021-08-19 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0028_checkbox_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkbox',
            name='id',
        ),
    ]
