# Generated by Django 3.2.6 on 2021-08-20 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0029_remove_checkbox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkbox',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkbox',
            name='canva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkbox_canva', to='bilans.canva'),
        ),
    ]
