# Generated by Django 3.2.6 on 2021-08-20 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0031_alter_checkbox_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilan',
            name='validation',
        ),
    ]
