# Generated by Django 3.2.6 on 2021-08-20 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0032_remove_bilan_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
