# Generated by Django 3.2.6 on 2021-08-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0033_canva_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canva',
            name='time',
        ),
    ]
