# Generated by Django 3.2.6 on 2021-08-20 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0035_canva_temps'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='today',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
