# Generated by Django 3.2.6 on 2021-08-20 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0037_remove_canva_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='today',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
