# Generated by Django 3.2.6 on 2021-08-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0038_canva_today'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canva',
            name='today',
        ),
    ]
