# Generated by Django 3.2.6 on 2021-08-22 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0039_remove_canva_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
