# Generated by Django 3.2.6 on 2021-08-22 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0040_maintenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenant',
        ),
        migrations.RemoveField(
            model_name='canva',
            name='temps',
        ),
    ]
