# Generated by Django 3.2.6 on 2021-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0041_auto_20210822_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canva',
            name='name',
            field=models.CharField(blank=True, default='test', max_length=255, null=True),
        ),
    ]
