# Generated by Django 3.2.6 on 2021-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0042_alter_canva_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkbox',
            name='validation',
            field=models.BooleanField(default=True),
        ),
    ]
