# Generated by Django 3.2.6 on 2021-08-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0043_alter_checkbox_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
