# Generated by Django 3.2.6 on 2021-08-22 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0044_maintenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='canva',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenant',
            name='now',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
