# Generated by Django 3.2.6 on 2021-08-22 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0046_alter_canva_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenant',
        ),
        migrations.AddField(
            model_name='canva',
            name='now',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
