# Generated by Django 3.2.6 on 2021-08-22 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0047_auto_20210822_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canva',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
