# Generated by Django 3.2.6 on 2021-08-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0048_alter_canva_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canva',
            name='now',
        ),
    ]
