# Generated by Django 3.2.6 on 2021-08-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0049_remove_canva_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='agregat',
            field=models.CharField(blank=True, default='testform', max_length=255, null=True),
        ),
    ]
