# Generated by Django 3.2.6 on 2021-09-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0058_auto_20210902_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='mois1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
