# Generated by Django 3.2.6 on 2021-09-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0061_auto_20210902_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan',
            name='evolution1',
            field=models.DecimalField(blank=True, decimal_places=2, default=' ', max_digits=20, null=True),
        ),
    ]
