# Generated by Django 3.2.6 on 2021-09-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilans', '0065_auto_20210905_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autre',
            name='ecart',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='evolution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='finmoisn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autre',
            name='finmoisn1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='SCF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bilan',
            name='evolution2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='ecart1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='ecart2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='evolution1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='evolution2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='finmois1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='finmois2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='mois1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='mois2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='moism',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tresorerie',
            name='moism1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
